### ISSUE TITLE
How can i integrate the sdk in laravel

### ISSUE THREAD

**Issue by Corymillz** [Flutterwave/Flutterwave-PHP-v3#1]
It is pretty clear how to integrate php libraries/sdk using something like composer require xyz/zyx.
How can i do this same using with this sdk because it is not in the documentation

**Comment by bajoski34** [comment]
Hi @Corymillz  There is actually a package for laravel. Check it out via the link https://github.com/kingflamez/laravelrave

**Comment by ankit-shah-logistic** [comment]
I am getting 500 error while implementing this SDK to PHP. Can you Please suggest or provide me documentation ?

**Comment by bajoski34** [comment]
HI @ankit-shah-logistic  Please read the readme file for the required setup process.

**Comment by Corvus97** [comment]
Hello @ankit-shah-logistic and @Corymillz,

Kindly share your issues and requests on our forum(https://developer.flutterwave.com/discuss) for more tips on their resolution.

Best regards,
Cornelius
