### ISSUE TITLE
installing php v-3

### ISSUE THREAD

**Issue by Loydtafireyi** [Flutterwave/Flutterwave-PHP-v3#10]
How do i require this sdk in my project. tried composer require Flutterwave-PHP-v3 and it seems not to be working

**Comment by obaydmir** [comment]
@Loydtafireyi this should work `composer require flutterwavedev/flutterwave-v3`.

**Comment by Loydtafireyi** [comment]
@obaydmir can you please include this in the readme file to avoid confusion for new users. Thank you.

**Comment by obaydmir** [comment]
> @obaydmir can you please include this in the readme file to avoid confusion for new users. Thank you.

Unfortunately, I'm not able to do that. I'm not part of their development team.

**Comment by salvationarinze** [comment]
@Loydtafireyi Thanks for the feedback. Will do

**Comment by kenkioko** [comment]
I have tried composer require. There is a conflict with "monolog/monolog": "^2.0". Your package currently requires "monolog/monolog": "1.*". Can you upgrade the required package?

**Comment by salvationarinze** [comment]
Thanks. Will do
