### ISSUE TITLE
Verify Transaction 

### ISSUE THREAD

**Issue by towoju5** [Flutterwave/Flutterwave-PHP-v3#11]
I tried to verify Transaction $verify = $verify = $payment->verifyTransaction($id); but i keep getting ` Array
(
    [status] => error
    [message] => No transaction was found for this id
    [data] => 
)`

even when i passed the ID  directly into the function i still get the same error.

**Comment by bajoski34** [comment]
Hi @towoju5  is this on testmode or live mode?

**Comment by towoju5** [comment]
> Hi @towoju5 is this on testmode or live mode?

Test mode
