### ISSUE TITLE
Please upgrade the Monolog library to version 2.x

### ISSUE THREAD

**Issue by daigo75** [Flutterwave/Flutterwave-PHP-v3#13]
The SDK still loads Monolog 1.x, which is an old version of the library, and it can't be used in any environment which requires the newer version. I would recommend to change file `composer.json` to reference Monolog 2.x and adjust your code to use the new version. 

The changes should be minimal, as Monolog 2.x is backward compatible and includes better support for PHP 7. You can find a list of the most important changes here: https://github.com/Seldaek/monolog/blob/master/UPGRADE.md. Such update would allow to use the Flutterwave SDK in modern PHP applications.

**Comment by bajoski34** [comment]
@daigo75 this issues has been resolved with latest update to the repo

**Comment by daigo75** [comment]
Excellent, thanks 👍

**Comment by bajoski34** [comment]
@daigo75 kindly close the issue

**Comment by daigo75** [comment]
Thanks for taking action so quickly. Just a note, if I may. Some customers reported that the latest version of Monolog 2.x requires PHP 7.2. Despite the fact that PHP 5.6 is now obsolete, quite a few servers run that version. Due to that, we modified our solutions to use the latest Monolog 1.x (currently 1.25.5), which works with both PHP 5.6 and 7.x.

I'm aware that this is a "step back", but it was necessary to maintain compatibility with the sites where an old version of PHP is still being used. I thought of letting you know, in case you come across some issues with Monolog 2.x and older PHP versions.
