### ISSUE TITLE
Integration with CI4

### ISSUE THREAD

**Issue by towoju5** [Flutterwave/Flutterwave-PHP-v3#17]
@Ekene-eze Please can you help with CI4 integration, have tried to but i keep having issue with monolog & .env {rave.php}
![Screen Shot 2020-11-04 at 3 56 38 AM](https://user-images.githubusercontent.com/40261626/98064130-dc2c3100-1e51-11eb-978f-d8db137b8ce1.png)

**Comment by bajoski34** [comment]
Hi @towoju5 Thank you for taking the time to report this, we really appreciate your help.
we are looking into the issue.

**Comment by towoju5** [comment]
Have been able to fix the issue, so i will like to close this issue. thanks

**Comment by seunex17** [comment]
Have you seen this yet?

https://github.com/seunex17/flutterwave-ci4
