### ISSUE TITLE
Pls update package on composer platform

### ISSUE THREAD

**Issue by spectrummfb** [Flutterwave/Flutterwave-PHP-v3#24]
Thanks for this package, it has really been helpful, can you guys pls update the package on Composer platform, several of the dependencies there are preventing installation using composer and I can see on the repo here that the composer.json file is more up to date.

Thanks

**Comment by japhyamg** [comment]
> Thanks for this package, it has really been helpful, can you guys pls update the package on Composer platform, several of the dependencies there are preventing installation using composer and I can see on the repo here that the composer.json file is more up to date.
> 
> Thanks

Please do you have any workaround for the installation?

**Comment by bajoski34** [comment]
Hi @japhyamg @spectrummfb this has been resolved.

**Comment by musicmeetscode** [comment]
Running into the same issue 
```
Problem 1
    - flutterwavedev/flutterwave-v3 1.0.0 requires monolog/monolog 1.* -> found monolog/monolog[1.0.0-RC1, ..., 1.x-dev] but the package is fixed to 2.3.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - flutterwavedev/flutterwave-v3 1.0.1 requires vlucas/phpdotenv ^2.5 -> found vlucas/phpdotenv[v2.5.0, ..., 2.6.x-dev] but the package is fixed to v5.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires flutterwavedev/flutterwave-v3 ^1.0 -> satisfiable by flutterwavedev/flutterwave-v3[1.0.0, 1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require flutterwavedev/flutterwave-v3:*" to figure out if any version is installable, or "composer require flutterwavedev/flutterwave-v3:^2.1" if you know which you need.
```

**Comment by bajoski34** [comment]
HI @musicmeetscode  run the command composer require  `composer require flutterwavedev/flutterwave-v3:dev-master`

**Comment by musicmeetscode** [comment]
Thanks. Worked

Running into this now
```
Error
Class "Flutterwave\MobileMoney" not found
http://127.0.0.1:8000/settings/payments/topup
```

Yet i can Ctl+Click into the class
