### ISSUE TITLE
Fatal error: Uncaught Dotenv\Exception\InvalidPathException:

### ISSUE THREAD

**Issue by chipalo1** [Flutterwave/Flutterwave-PHP-v3#28]
How can I solve this problem?

Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read any of the environment file(s) at [C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\library/../\.env]. in C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\vendor\vlucas\phpdotenv\src\Store\FileStore.php:68 Stack trace: #0 C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\vendor\vlucas\phpdotenv\src\Dotenv.php(222): Dotenv\Store\FileStore->read() #1 C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\library\rave.php(17): Dotenv\Dotenv->load() #2 C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\processPayment.php(11): include('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\tangwa\Flutterwave-PHP-v3-master\vendor\vlucas\phpdotenv\src\Store\FileStore.php on line 68

**Comment by bajoski34** [comment]
HI @chipalo1 Thanks for reaching out. please kindly that you have create a .env file to so the SDK is able to read your environment variables.

Thanks
